### ISSUE TITLE
fail to import project to intelliJ

### ISSUE THREAD

**Issue by BeneyKim** [tigerbalm/cmu-not-yet#1]
Cannot open the project with intelliJ,

Please find the error message as below.

**Supplied String module notation 'org.lge.notyet.ui.MainDialog' is invalid**. Example notations: 'org.gradle:gradle-core:2.2', 'org.mockito:mockito-core:1.9.5:javadoc'.  Consult IDE log for more details (Help | Show Log)

**Comment by gladvindurai** [comment]
Application's build.gradle file was having wrong entries for build and run. 
These are not required to have gradle build.
