### ISSUE TITLE
[T-1][NOT-IMPLEMENTED] Server redendancy

### ISSUE THREAD

**Issue by megatin74** [tigerbalm/cmu-not-yet#2]
If primary server is unavailibe because of power down or network trouble, secondary server should work within guaratted time

Test Sequence
1. Tester operates sure-park system generally.
2. Tester shut down  power or pull off network cable of the primary server

**Comment by reshout** [comment]
It works when we terminate one of server process. But we need to check another case; when make network unavailable.

**Comment by BeneyKim** [comment]
working well :) for test case 2.
