### ISSUE TITLE
[SSD] Make Reservation

### ISSUE THREAD

**Issue by BeneyKim** [tigerbalm/cmu-not-yet#22]

**Comment by BeneyKim** [comment]
title Make Reservation

participant Driver
participant :SurePark\nReservation\nSystem as driver
participant :SurePark\nProcessing\nSystem as server
participant ":Database" as db
participant ":CCAS" as cardsystem

Driver->driver :Make a reservation
activate driver
driver->server: Request Reservation
deactivate driver
server->db: Retreive Drier's credit card information
db-->server: credit card iformation

server->cardsystem: Request to validate\ncredit card iformation
cardsystem-->server: valdidation result

server-->driver: reservation result
driver-->Driver: Show reservation result
activate driver

**Comment by wonhongkwon** [comment]
This has been merged into the document

**Comment by wonhongkwon** [comment]
participant Driver
participant :SurePark\nReservation\nSystem as driver
participant :SurePark\nProcessing\nSystem as server
participant ":Database" as db
participant ":CCPS" as cardsystem

Driver->driver :Make a reservation
activate driver
driver->server: Request Reservation
deactivate driver
server->db: Retreive Drier's credit card information
db-->server: credit card iformation

server->cardsystem: Request to validate\ncredit card iformation
cardsystem-->server: valdidation result

server-->driver: reservation result
driver-->Driver: Show reservation result
activate driver

**Comment by wonhongkwon** [comment]
participant Driver
participant SurePark\nReservation\nSystem as driver
participant SurePark\nProcessing\nSystem as server
participant "Database" as db
participant "CCPS" as cardsystem

Driver->driver :Make a reservation
activate driver
driver->server: Request Reservation
deactivate driver
server->db: Retreive Drier's credit card information
db-->server: credit card iformation

server->cardsystem: Request to validate\ncredit card iformation
cardsystem-->server: valdidation result

server-->driver: reservation result
driver-->Driver: Show reservation result
activate driver
