### ISSUE TITLE
[SSD] Passing Entry Gate

### ISSUE THREAD

**Issue by BeneyKim** [tigerbalm/cmu-not-yet#23]

**Comment by tigerbalm** [comment]
@wonhongkwon 
please refer to ssd about "passing entry gate"

https://www.websequencediagrams.com/

---

title Passing entry gate

participant "CarDetector" as car
participant "Facility\nController" as fc
participant "Kiosk\nProcess" as kiosk
participant "MQTT\nBroker" as mq
participant "Server\nProcess" as server

car -> fc : approach detected
fc -> kiosk : input reservation number
kiosk --> fc : number
fc -> mq : confirm reservation number event 
mq -> server : confirm reservation number event
server --> mq : (ok, slot)
mq --> fc : (ok, slot)

**Comment by tigerbalm** [comment]
@wonhongkwon
this is latest.

## https://www.websequencediagrams.com/

title Passing entry gate

participant "Facility\nController" as fc
participant "Facility User I/F" as kiosk
participant "MQTT\nBroker" as mq
participant "Sure-Park \nProcessingSystem" as server

note left of fc : car\ndetected
fc -> kiosk : req. input number
kiosk --> fc : number
fc -> mq : confirm reservation number event
mq -> server : confirm reservation number event
server --> mq : (ok, slot)
mq --> fc : (ok, slot)

**Comment by wonhongkwon** [comment]
This has been merged into the document
