### ISSUE TITLE
[SSD] Parking

### ISSUE THREAD

**Issue by BeneyKim** [tigerbalm/cmu-not-yet#24]

**Comment by tigerbalm** [comment]
@wonhongkwon

## https://www.websequencediagrams.com/

title Parking a car

participant "Facility\nController" as fc
participant "MQTT\nBroker" as mq
participant "Sure-Park\nProcessing" as server
participant "Facility\nManager" as at

note left of fc : car is \nparked at slot#
fc -> mq : car parked\n(slot#,reservation#)
mq -> server : car parked\n(slot#,reservation#)
server -> at : updated\n(facility#)
at -> server : query status
server --> at : slot status

**Comment by wonhongkwon** [comment]
This has been merged into the document
