### ISSUE TITLE
[SSD] Passing the exit gate

### ISSUE THREAD

**Issue by BeneyKim** [tigerbalm/cmu-not-yet#25]

**Comment by tigerbalm** [comment]
@wonhongkwon 

## https://www.websequencediagrams.com/

title Leaving parking lot

participant "Facility\nController" as fc
participant "MQTT\nBroker" as mq
participant "Sure-Park\nProcessing" as server
participant "CCAS" as card
participant "Facility\nManager" as at

note left of fc : car is detected\nat exit gate
fc -> mq : request payment\n(slot#)
mq -> server : request payment\n(slot#)
server -> card : request payment\n(card info)
card --> server : ok
server --> mq : success
server -> at : updated\n(facility#)
at -> server : query status
server --> at : slot status
mq --> fc : success
note over fc : open gate\nwait leaving

**Comment by wonhongkwon** [comment]
participant "Facility\nController" as fc
participant "MQTT\nBroker" as mq
participant "Sure-Park\nProcessing" as server
participant "CCPS" as card
participant "Facility\nManager" as at

note left of fc : car is detected\nat exit gate
fc -> mq : request payment\n(slot#)
mq -> server : request payment\n(slot#)
server -> card : request payment\n(card info)
card --> server : ok
server --> mq : success
server -> at : updated\n(facility#)
at -> server : query status
server --> at : slot status
mq --> fc : success
note over fc : open gate\nwait leaving

**Comment by wonhongkwon** [comment]
This has been merged into the document.
