### ISSUE TITLE
[SSD] Server Passive Redundancy

### ISSUE THREAD

**Issue by BeneyKim** [tigerbalm/cmu-not-yet#26]

**Comment by BeneyKim** [comment]
title SurePark Processing System Redundancy Algorithm

participant 1:SurePark\nProcessing\nSystem as surePark1
participant 2:SurePark\nProcessing\nSystem as surePark2
participant 3:SurePark\nProcessing\nSystem as surePark3
participant 4:SurePark\nProcessing\nSystem as surePark4

SurePark Manaer->_surePark1:Add new system
SurePark Manaer->_surePark2:Add new system
note right of surePark1: Two SurePark Processiong Sytems start running at almost same time.\nEach system starts to contend to be master after randomized delay
surePark1->surePark1: Wait randomized contention time\n(<5 secs)
activate surePark1
surePark2->surePark2: Wait randomized contention time\n(<5 secs)

activate surePark2
note right of surePark2: Does not send reponse,\nbecause this is not active.
surePark1->surePark2: Master Solitation
deactivate surePark1

surePark1->surePark1: Wait randomized master conf. time\n(3~5 secs)
activate surePark1

SurePark Manaer->*surePark3:Add new system
surePark3->surePark3: Wait randomized contention time\n(<5 secs)
activate surePark3

note left of surePark1: Does not send reponse,\nbecause this is not active.
surePark2->surePark1: Master Solitation
surePark2->surePark3: Master Solitation
note right of surePark3: Does not send reponse,\nbecause this is not active.
deactivate surePark2

surePark2->surePark2: Wait randomized master conf. time\n(3~5 secs)
activate surePark2

surePark1->surePark2: Master Advertisement
surePark1->surePark3: Master Advertisement
note right of surePark1: 1:SurePark Processiong System is now Master. The others are all Slave.
deactivate surePark1
deactivate surePark2
deactivate surePark3

SurePark Manaer->*surePark4:Add new system
surePark3->surePark4: Wait randomized contention time\n(<5 secs)
activate surePark4
surePark4->surePark3: Master Solitation
surePark4->surePark2: Master Solitation
surePark4->surePark1: Master Solitation
surePark1->surePark4: Master Advertisement
note right of surePark4: 4:SurePark Processiong System is Slave.
deactivate surePark4

**Comment by BeneyKim** [comment]
I updated and make two SSD scenario for this case.

title SurePark Processing System Redundancy Algorithm : Contention

participant 1:SurePark\nProcessing\nSystem as surePark1
participant 2:SurePark\nProcessing\nSystem as surePark2
participant 3:SurePark\nProcessing\nSystem as surePark3

SurePark Manaer->_surePark1:Add new system
SurePark Manaer->_surePark2:Add new system
note right of surePark1: Two SurePark Processiong Sytems\nstart running at almost same time.\nEach system starts to contend\nto be master after randomized delay
surePark1->surePark1: Wait randomized\ncontention time\n(<5 secs)
activate surePark1
surePark2->surePark2: Wait randomized\ncontention time\n(<5 secs)

activate surePark2
note right of surePark2: Does not send reponse,\nbecause this is not active.
surePark1->surePark2: Master Solitation
deactivate surePark1

surePark1->surePark1: Wait randomized master conf. time\n(3~5 secs)
activate surePark1

SurePark Manaer->*surePark3:Add new system
surePark3->surePark3: Wait randomized\ncontention time\n(<5 secs)
activate surePark3

note left of surePark1: Does not send reponse,\nbecause this is not active.
surePark2->surePark1: Master Solitation
surePark2->surePark3: Master Solitation
note right of surePark3: Does not send reponse,\nbecause this is not active.
deactivate surePark2

surePark2->surePark2: Wait randomized\nmaster conf. time\n(3~5 secs)
activate surePark2

surePark1->surePark2: Master Advertisement
deactivate surePark2
surePark1->surePark3: Master Advertisement
note right of surePark1: 1:SurePark Processiong\nSystem is now Master.\nThe others are all Slave.
deactivate surePark1
deactivate surePark3

**Comment by BeneyKim** [comment]
The other one is

title SurePark Processing System Redundancy Algorithm : New system

participant 1:SurePark\nProcessing\nSystem as surePark1
participant 4:SurePark\nProcessing\nSystem as surePark4

SurePark Manaer->*surePark1:Add new system
note right of surePark1:  1:SurePark Processiong System is Master.
activate surePark1

SurePark Manaer->*surePark4:Add new system
activate surePark4
surePark4->surePark1: Master Solitation
surePark1->surePark4: Master Advertisement
note right of surePark4: 4:SurePark Processiong System is Slave.
deactivate surePark4

**Comment by BeneyKim** [comment]
[SSD1]

title SurePark Processing System Redundancy Algorithm : Contention

participant 1:SurePark\nProcessing\nSystem as surePark1
participant 2:SurePark\nProcessing\nSystem as surePark2
participant 3:SurePark\nProcessing\nSystem as surePark3
participant :Broker as broker

broker->surePark1:Master server is down
broker->surePark2:Master server is down
surePark1->surePark1: Wait randomized\ncontention time\n(<5 secs)
activate surePark1
surePark2->surePark2: Wait randomized\ncontention time\n(<5 secs)
activate surePark2
surePark1->broker: Master Solitation
broker->surePark2: Master Solitation
note over surePark2: Does not send reponse,\nbecause this is not active.
deactivate surePark1

surePark1->surePark1: Wait randomized master conf. time\n(3~5 secs)
activate surePark1

:SurePark Manaer->*surePark3:Add new system
surePark3->surePark3: Wait randomized\ncontention time\n(<5 secs)
activate surePark3

surePark2->broker: Master Solitation
broker->surePark1: Master Solitation
broker->surePark3: Master Solitation
note over surePark1: Does not send reponse,\nbecause this is not active.
note over surePark3: Does not send reponse,\nbecause this is not active.
deactivate surePark2

surePark2->surePark2: Wait randomized\nmaster conf. time\n(3~5 secs)
activate surePark2

surePark1->broker: Master Advertisement
broker->surePark2: Master Advertisement
deactivate surePark2
broker->surePark3: Master Advertisement
note over surePark1: 1:SurePark Processiong\nSystem is now Master.\nThe others are all Slave.
deactivate surePark3

[SSD2]

title SurePark Processing System Redundancy Algorithm : New system

participant 1:SurePark\nProcessing\nSystem as surePark1
participant 4:SurePark\nProcessing\nSystem as surePark4
participant :Broker as broker

SurePark Manaer->*surePark1:Add new system
note over surePark1:  1:SurePark Processiong\nSystem is Master.
activate surePark1

SurePark Manaer->*surePark4:Add new system
activate surePark4
surePark4->broker: Master Solitation
broker->surePark1: Master Solitation
surePark1->broker: Master Advertisement
broker->surePark4: Master Advertisement
note over surePark4: 4:SurePark Processiong\nSystem is Slave.
deactivate surePark4

**Comment by wonhongkwon** [comment]
This has been merged into the document

**Comment by wonhongkwon** [comment]
participant 1:SurePark\nProcessing\nSystem as surePark1
participant 2:SurePark\nProcessing\nSystem as surePark2
participant 3:SurePark\nProcessing\nSystem as surePark3
participant :Broker as broker

broker->surePark1:Master server is down
broker->surePark2:Master server is down
surePark1->surePark1: Wait randomized\ncontention time\n(<5 secs)
activate surePark1
surePark2->surePark2: Wait randomized\ncontention time\n(<5 secs)
activate surePark2
surePark1->broker: Master Solitation
broker->surePark2: Master Solitation
note over surePark2: Does not send reponse,\nbecause this is not active.
deactivate surePark1

surePark1->surePark1: Wait randomized master conf. time\n(3~5 secs)
activate surePark1

:SurePark Manager->*surePark3:Add new system
surePark3->surePark3: Wait randomized\ncontention time\n(<5 secs)
activate surePark3

surePark2->broker: Master Solitation
broker->surePark1: Master Solitation
broker->surePark3: Master Solitation
note over surePark1: Does not send reponse,\nbecause this is not active.
note over surePark3: Does not send reponse,\nbecause this is not active.
deactivate surePark2

surePark2->surePark2: Wait randomized\nmaster conf. time\n(3~5 secs)
activate surePark2

surePark1->broker: Master Advertisement
broker->surePark2: Master Advertisement
deactivate surePark2
broker->surePark3: Master Advertisement
note over surePark1: 1:SurePark Processiong\nSystem is now Master.\nThe others are all Slave.
deactivate surePark3

**Comment by wonhongkwon** [comment]
participant 1:SurePark\nProcessing\nSystem as surePark1
participant 4:SurePark\nProcessing\nSystem as surePark4
participant :Broker as broker

SurePark Manager->*surePark1:Add new system
note over surePark1: 1:SurePark Processiong\nSystem is Master.
activate surePark1

SurePark Manager->*surePark4:Add new system
activate surePark4
surePark4->broker: Master Solitation
broker->surePark1: Master Solitation
surePark1->broker: Master Advertisement
broker->surePark4: Master Advertisement
note over surePark4: 4:SurePark Processiong\nSystem is Slave.
deactivate surePark4

**Comment by wonhongkwon** [comment]
participant 1:SurePark\nProcessing\nSystem as surePark1
participant 2:SurePark\nProcessing\nSystem as surePark2
participant 3:SurePark\nProcessing\nSystem as surePark3
participant MQTT\nBroker as broker

broker->surePark1:Master server is down
broker->surePark2:Master server is down
surePark1->surePark1: Wait randomized\ncontention time\n(<5 secs)
activate surePark1
surePark2->surePark2: Wait randomized\ncontention time\n(<5 secs)
activate surePark2
surePark1->broker: Master Solitation
broker->surePark2: Master Solitation
note over surePark2: Does not send reponse,\nbecause this is not active.
deactivate surePark1

surePark1->surePark1: Wait randomized master conf. time\n(3~5 secs)
activate surePark1

SurePark\nManager->*surePark3:Add new system
surePark3->surePark3: Wait randomized\ncontention time\n(<5 secs)
activate surePark3

surePark2->broker: Master Solitation
broker->surePark1: Master Solitation
broker->surePark3: Master Solitation
note over surePark1: Does not send reponse,\nbecause this is not active.
note over surePark3: Does not send reponse,\nbecause this is not active.
deactivate surePark2

surePark2->surePark2: Wait randomized\nmaster conf. time\n(3~5 secs)
activate surePark2

surePark1->broker: Master Advertisement
broker->surePark2: Master Advertisement
deactivate surePark2
broker->surePark3: Master Advertisement
note over surePark1: 1:SurePark Processiong\nSystem is now Master.\nThe others are all Slave.
deactivate surePark3

**Comment by wonhongkwon** [comment]
participant 1:SurePark\nProcessing\nSystem as surePark1
participant 2:SurePark\nProcessing\nSystem as surePark2
participant 3:SurePark\nProcessing\nSystem as surePark3
participant MQTT\nBroker as broker

broker->surePark1:Master server is down
broker->surePark2:Master server is down
surePark1->surePark1: Wait randomized\ncontention time\n(<5 secs)
activate surePark1
surePark2->surePark2: Wait randomized\ncontention time\n(<5 secs)
activate surePark2
surePark1->broker: Master Solitation
broker->surePark2: Master Solitation
note over surePark2: Does not send reponse,\nbecause this is not active.
deactivate surePark1

surePark1->surePark1: Wait\nrandomized\nmaster conf. time\n(3~5 secs)
activate surePark1

SurePark\nManager->*surePark3:Add new system
surePark3->surePark3: Wait randomized\ncontention time\n(<5 secs)
activate surePark3

surePark2->broker: Master Solitation
broker->surePark1: Master Solitation
broker->surePark3: Master Solitation
note over surePark1: Does not send reponse,\nbecause this is not active.
note over surePark3: Does not send reponse,\nbecause this is not active.
deactivate surePark2

surePark2->surePark2: Wait randomized\nmaster conf. time\n(3~5 secs)
activate surePark2

surePark1->broker: Master Advertisement
broker->surePark2: Master Advertisement
deactivate surePark2
broker->surePark3: Master Advertisement
note over surePark1: 1:SurePark Processiong\nSystem is now Master.\nThe others are all Slave.
deactivate surePark3

**Comment by wonhongkwon** [comment]
participant 1:SurePark\nProcessing\nSystem as surePark1
participant 2:SurePark\nProcessing\nSystem as surePark2
participant 3:SurePark\nProcessing\nSystem as surePark3
participant MQTT\nBroker as broker

broker->surePark1:Master server is down
broker->surePark2:Master server is down
surePark1->surePark1: Wait randomized\ncontention time\n(<5 secs)
activate surePark1
surePark2->surePark2: Wait randomized\ncontention time\n(<5 secs)
activate surePark2
surePark1->broker: Master Solicitation
broker->surePark2: Master Solicitation
note over surePark2: Does not send reponse,\nbecause this is not active.
deactivate surePark1

surePark1->surePark1: Wait\nrandomized\nmaster conf. time\n(3~5 secs)
activate surePark1

SurePark\nManager->*surePark3:Add new system
surePark3->surePark3: Wait randomized\ncontention time\n(<5 secs)
activate surePark3

surePark2->broker: Master Solicitation
broker->surePark1: Master Solicitation
broker->surePark3: Master Solicitation
note over surePark1: Does not send reponse,\nbecause this is not active.
note over surePark3: Does not send reponse,\nbecause this is not active.
deactivate surePark2

surePark2->surePark2: Wait randomized\nmaster conf. time\n(3~5 secs)
activate surePark2

surePark1->broker: Master Advertisement
broker->surePark2: Master Advertisement
deactivate surePark2
broker->surePark3: Master Advertisement
note over surePark1: 1:SurePark Processiong\nSystem is now Master.\nThe others are all Slave.
deactivate surePark3

**Comment by wonhongkwon** [comment]
participant 1:SurePark\nProcessing\nSystem as surePark1
participant 4:SurePark\nProcessing\nSystem as surePark4
participant MQTT\nBroker as broker

SurePark\nManager->*surePark1:Add new system
note over surePark1: 1:SurePark Processiong\nSystem is Master.
activate surePark1

SurePark Manager->*surePark4:Add new system
activate surePark4
surePark4->broker: Master Solitation
broker->surePark1: Master Solitation
surePark1->broker: Master Advertisement
broker->surePark4: Master Advertisement
note over surePark4: 4:SurePark Processing\nSystem is Slave.
deactivate surePark4

**Comment by wonhongkwon** [comment]
participant 1:SurePark\nProcessing\nSystem as surePark1
participant 4:SurePark\nProcessing\nSystem as surePark4
participant MQTT\nBroker as broker

SurePark\nManager->*surePark1:Add new system
note over surePark1: 1:SurePark Processiong\nSystem is Master.
activate surePark1

SurePark Manager->*surePark4:Add new system
activate surePark4
surePark4->broker: Master Solicitation
broker->surePark1: Master Solicitation
surePark1->broker: Master Advertisement
broker->surePark4: Master Advertisement
note over surePark4: 4:SurePark Processing\nSystem is Slave.
deactivate surePark4
