### ISSUE TITLE
[SSD] Owner check statistics.

### ISSUE THREAD

**Issue by BeneyKim** [tigerbalm/cmu-not-yet#30]

**Comment by gladvindurai** [comment]
Working on it.
ToDo
- more settings menu (from&to datetime)
- gui report

**Comment by gladvindurai** [comment]
Initial sequence diagram
title Owner check statistics

opt Collect request from "Owner"
Owner->Sure-Park Statistics Viewer: Choose a "report type"
Sure-Park Statistics Viewer->+Query: Get "more settings" UI
Query-->-Sure-Park Statistics Viewer: 
Owner-->Sure-Park Statistics Viewer: Input "more settings"
end
opt Network Communication
Sure-Park Statistics Viewer->+Query: Send "report type" & "More settings"
Query-->-Sure-Park Statistics Viewer: SQL Query
Sure-Park Statistics Viewer->Libcomm: Session Identifier, SQL Query
note right of Libcomm: MQTT broker (mosquitto)
Libcomm->Sure-Park Statistics Viewer: Report Data
end
opt Display to "Owner"
Sure-Park Statistics Viewer->+Query:Compute the display format
Query-->-Sure-Park Statistics Viewer:
note right of Sure-Park Statistics Viewer: Display the report
Owner-->Sure-Park Statistics Viewer: Choose graphical report
Sure-Park Statistics Viewer->+Query:Compute the graphical format
Query-->-Sure-Park Statistics Viewer:
note right of Sure-Park Statistics Viewer: Display the graphical report
end

**Comment by gladvindurai** [comment]
title Owner check statistics

Owner->Sure-Park Statistics Viewer: Choose a "report type"
Sure-Park Statistics Viewer->Sure-Park Statistics Viewer: Get "more settings" UI
Owner-->Sure-Park Statistics Viewer: Input "more settings"
Sure-Park Statistics Viewer->Libcomm: Session Identifier, SQL Query
Libcomm->MQTT broker (mosquitto): DB Query Request
MQTT broker (mosquitto)->Libcomm (server): DB Query Request
Libcomm (server)->Sure-Park Processing System: DB Query Request
Sure-Park Processing System->Database: SQL Query
Database->Sure-Park Processing System: SQL Result
Sure-Park Processing System->Libcomm (server): DB Query Response
Libcomm (server)->MQTT broker (mosquitto): DB Query Response
MQTT broker (mosquitto)->Libcomm: DB Query Response
Libcomm->Sure-Park Statistics Viewer: SQL Result
note right of Sure-Park Statistics Viewer
    Display in the 
    required format
end note

**Comment by wonhongkwon** [comment]
This has been merged into the document.

**Comment by wonhongkwon** [comment]
Owner->Sure-Park\nStatistics\nViewer: Choose a "report type"
Sure-Park\nStatistics\nViewer->Sure-Park\nStatistics\nViewer: Get "more settings" UI
Owner-->Sure-Park\nStatistics\nViewer: Input "more settings"
Sure-Park\nStatistics\nViewer->Communication\nManager: Session Identifier, SQL Query
Communication\nManager->MQTT broker (mosquitto): DB Query Request
MQTT broker (mosquitto)->Communication\nManager (server): DB Query Request
Communication\nManager (server)->Sure-Park\nProcessing\nSystem: DB Query Request
Sure-Park\nProcessing\nSystem->Database: SQL Query
Database->Sure-Park\nProcessing\nSystem: SQL Result
Sure-Park\nProcessing\nSystem->Communication\nManager (server): DB Query Response
Communication\nManager (server)->MQTT broker (mosquitto): DB Query Response
MQTT broker (mosquitto)->Communication\nManager: DB Query Response
Communication\nManager->Sure-Park\nStatistics\nViewer: SQL Result
note right of Sure-Park\nStatistics\nViewer
Display in the 
required format
end note

**Comment by wonhongkwon** [comment]
renamed

**Comment by wonhongkwon** [comment]
Owner->Sure-Park\nStatistics\nViewer: Choose a "report type"
Sure-Park\nStatistics\nViewer->Sure-Park\nStatistics\nViewer: Get "more settings" UI
Owner-->Sure-Park\nStatistics\nViewer: Input "more settings"
Sure-Park\nStatistics\nViewer->MQTT broker: Session Identifier, SQL Query
MQTT broker->Sure-Park\nProcessing\nSystem: DB Query Request
Sure-Park\nProcessing\nSystem->Database: SQL Query
Database->Sure-Park\nProcessing\nSystem: SQL Result
Sure-Park\nProcessing\nSystem->MQTT broker: DB Query Response
MQTT broker->Sure-Park\nStatistics\nViewer: SQL Result
note right of Sure-Park\nStatistics\nViewer
Display in the 
required format
end note

**Comment by wonhongkwon** [comment]
refined

**Comment by wonhongkwon** [comment]
Owner->Sure-Park\nStatistics\nViewer: Choose a "report type"
Sure-Park\nStatistics\nViewer->Sure-Park\nStatistics\nViewer: Get "more settings" UI
Owner-->Sure-Park\nStatistics\nViewer: Input "more settings"
Sure-Park\nStatistics\nViewer->MQTT\nBroker: Session Identifier, SQL Query
MQTT\nBroker->Sure-Park\nProcessing\nSystem: DB Query Request
Sure-Park\nProcessing\nSystem->Database: SQL Query
Database->Sure-Park\nProcessing\nSystem: SQL Result
Sure-Park\nProcessing\nSystem->MQTT\nBroker: DB Query Response
MQTT\nBroker->Sure-Park\nStatistics\nViewer: SQL Result
note right of Sure-Park\nStatistics\nViewer
Display in the 
required format
end note
