### ISSUE TITLE
[T-5][NOT-IMPLEMENTED] Server sign up

### ISSUE THREAD

**Issue by megatin74** [tigerbalm/cmu-not-yet#4]

**Comment by BeneyKim** [comment]
Is this same as https://github.com/tigerbalm/cmu-not-yet/issues/3 ?

**Comment by megatin74** [comment]
I remove this case in server side.

**Comment by megatin74** [comment]
I remove this case in server side.

**Comment by megatin74** [comment]
I remove this case in server side.
